version: "3.9"

services:

  api:

    build:

      context: .

      dockerfile: backend/Dockerfile

    container_name: go-clean-architecture

    ports:

      - 8080:5000

    restart: unless-stopped

